### PR TITLE
Add dropdown container class options

### PR DESCRIPTION
**Pull request by simmerz**
A change to allow the dropdown menu to take a class, so that right aligned menus can be created.

### CODE REVIEW

**Comment by manuelmeurer** [comment]
Thanks, @simmerz! Since all other keys except `class` would be unused in `dropdown_options`, how about having a `wrapper_class` instead that is set to `dropdown-menu` by default in the method signature?

**Comment by manuelmeurer** [comment]
Also, could you squash all commits into one? Thanks!

**Comment by simmerz** [comment]
@manuelmeurer that's all done :)

**Comment by manuelmeurer** [comment]
I think removing the `wrapper_class` from the `list_item_options` needs to happen before `list_item_attributes = attributes_for_tag(list_item_options)`, otherwise it will be part of `list_item_attributes`.

**Comment by KODerFunk** [comment]
@simmerz, @manuelmeurer Hi! This is a very necessary feature, right now, forced to use this fork :(

**Comment by manuelmeurer** [comment]
v3.0.4 is released. 🎉

**Pull request merged**
